-- Cài đặt Extension hỗ trợ UUID (thường được bật sẵn trên Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-------------------------------------------------------------------------
-- 1. BẢNG CÂU HỎI (questions)
-------------------------------------------------------------------------
CREATE TABLE public.questions (
  -- Sử dụng bigint tương thích với cơ chế Date.now() hiện tại của ứng dụng
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  subject text NOT NULL,                                  -- Môn học (VD: 'Tin học', 'Công nghệ')
  grade text NOT NULL,                                    -- Khối lớp (VD: '3', '4', '5')
  lesson text,                                            -- Tên bài học (Có thể trống)
  text text NOT NULL,                                     -- Nội dung câu hỏi
  type text NOT NULL DEFAULT 'multiple_choice',             -- Loại ('multiple_choice', 'short_answer')
  
  options jsonb,                                          -- Trắc nghiệm: Mảng JSON ["A", "B", "C", "D"]
  correct_index smallint,                                 -- Trắc nghiệm: Vị trí đáp án đúng (0, 1, 2, 3)
  
  short_answers jsonb,                                    -- Tự luận: Mảng JSON chữ được chấp nhận ["Đúng 1", "Đúng 2"]
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-------------------------------------------------------------------------
-- 2. BẢNG LỊCH SỬ THI / BẢNG XẾP HẠNG (quiz_history)
-------------------------------------------------------------------------
CREATE TABLE public.quiz_history (
  -- Dùng UUID thay vì Date.now().toString() để không bị trùng lặp trên môi trường nhiều người dùng
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  
  student_name text NOT NULL,                             -- Tên người thi
  class_name text NOT NULL,                               -- Tên lớp (VD: 3A)
  grade text NOT NULL,                                    -- Khối lớp
  subject text NOT NULL,                                  -- Môn thi
  
  score integer NOT NULL,                                 -- Số câu trả lời đúng
  total_questions integer NOT NULL,                       -- Tổng số câu hỏi trong đề
  
  -- Supabase sử dụng timestamp cho date, ta sẽ format lại trên Frontend
  date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-------------------------------------------------------------------------
-- 3. CẤU HÌNH BẢO MẬT (ROW LEVEL SECURITY - RLS)
-------------------------------------------------------------------------
-- Bật RLS cho cả 2 bảng (Yêu cầu bắt buộc của Supabase để bảo mật)
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_history ENABLE ROW LEVEL SECURITY;

-- CHO PHÉP MỌI NGƯỜI ĐỌC (Để học sinh lấy được câu hỏi thi, xem được bảng xếp hạng)
CREATE POLICY "Cho phép tất cả mọi người tải câu hỏi" 
  ON public.questions FOR SELECT USING (true);

CREATE POLICY "Cho phép tất cả mọi người xem xếp hạng" 
  ON public.quiz_history FOR SELECT USING (true);

-- CHO PHÉP HỌC SINH LƯU KẾT QUẢ THI
CREATE POLICY "Cho phép tất cả mọi người lưu kết quả thi" 
  ON public.quiz_history FOR INSERT WITH CHECK (true);

-- CHO PHÉP QUẢN TRỊ VIÊN THÊM/SỬA/XÓA CÂU HỎI
-- Tạm thời để (true) dùng cho App này. Sau này khi kết hợp với Supabase Auth,
-- bạn có thể thay USING(true) thành USING(auth.role() = 'authenticated') nhé.
CREATE POLICY "Cho phép mọi người quản trị câu hỏi (Tạm thời)" 
  ON public.questions FOR ALL USING (true) WITH CHECK (true);
